#!/data/data/com.anwind/files/usr/bin/bash
# AnWind wineboot 包装器（APK assets 自动部署，勿手改）
# 等价: anwind-wine wineboot [args]（-i 初始化/更新前缀，容器自持环境）
exec /data/data/com.anwind/files/rootfs/usr/bin/anwind-wine wineboot "$@"
