# ============================================================
# AnWind desktop integration (auto-generated by AnWind installer)
# 在真实 Termux shell 中提供 AnWind 桌面命令：
#   theme win95|xp|win7|win10|win11   切换桌面主题
#   start <app>                      打开 AnWind 应用
#   apps                             列出可打开的应用
#   open <url>                       用 AnWind 浏览器打开网址
#   winver                           显示 AnWind 版本信息
# 原理：命令写入 FIFO，由 App 主进程读取并执行。
# ============================================================

ANWIND_CMD_FIFO="$PREFIX/var/anwind.cmd"

_anwind_send() {
    if [ -p "$ANWIND_CMD_FIFO" ]; then
        ( printf '%s\n' "$*" > "$ANWIND_CMD_FIFO" & ) 2>/dev/null
    else
        echo "anwind: 命令桥不可用（App 未运行或 FIFO 缺失）" >&2
        return 1
    fi
}

theme() {
    if [ $# -eq 0 ]; then
        echo "用法: theme win95|xp|win7|win10|win11"
        return 1
    fi
    _anwind_send "theme $*"
}

start() {
    if [ $# -eq 0 ]; then
        echo "用法: start <应用名>，运行 apps 查看列表"
        return 1
    fi
    _anwind_send "start $*"
}

apps() {
    _anwind_send "apps"
}

open() {
    if [ $# -eq 0 ]; then
        echo "用法: open <url>"
        return 1
    fi
    _anwind_send "open $*"
}

winver() {
    _anwind_send "winver"
    echo "AnWind ${ANWIND_VERSION:-2.22.1} (Termux ${TERMUX_VERSION:-0.118.0} 移植)"
}
