# ============================================================
# AnWind desktop integration (auto-generated by AnWind installer)
# 在真实 Termux shell 中提供 AnWind 桌面命令：
#   theme win95|xp|win7|win10|win11   切换桌面主题
#   start <app>                      打开 AnWind 应用
#   apps                             列出可打开的应用
#   open <url>                       用 AnWind 浏览器打开网址
#   winver                           显示 AnWind 版本信息
# 原理：命令写入 FIFO，由 App 主进程读取并执行。
# ============================================================

# ---- dpkg 包装器自愈（fix7 兜底，静默）----
# dpkg 包自升级会用新真身 ELF 覆盖 bin/dpkg（包装器副本）。apt 经
# apt.conf.d/99anwind 走 libexec/anwind/dpkg 不受影响，但用户直接
# 调用的 bin/dpkg 需要恢复：若其为 ELF（被覆盖），先提升为
# dpkg.real（保持版本最新），再从包装器本体恢复副本。
_anwind_heal_dpkg() {
    _bin="$PREFIX/bin/dpkg"
    _wrap="$PREFIX/libexec/anwind/dpkg"
    _real="$PREFIX/libexec/anwind/dpkg.real"
    [ -f "$_wrap" ] || return 0
    if [ -f "$_bin" ]; then
        _magic=$(head -c 4 "$_bin" 2>/dev/null | od -An -tx1 2>/dev/null | tr -d ' \n')
        if [ "$_magic" = "7f454c46" ]; then
            if [ ! -f "$_real" ] || [ "$_bin" -nt "$_real" ]; then
                cp -f "$_bin" "$_real.tmp" 2>/dev/null \
                    && chmod 700 "$_real.tmp" 2>/dev/null \
                    && mv -f "$_real.tmp" "$_real" 2>/dev/null
            fi
        fi
    fi
    if ! cmp -s "$_wrap" "$_bin" 2>/dev/null; then
        cp -f "$_wrap" "$_bin.tmp" 2>/dev/null \
            && chmod 700 "$_bin.tmp" 2>/dev/null \
            && mv -f "$_bin.tmp" "$_bin" 2>/dev/null
    fi
    return 0
}
_anwind_heal_dpkg
unset -f _anwind_heal_dpkg

ANWIND_CMD_FIFO="$PREFIX/var/anwind.cmd"

_anwind_send() {
    if [ -p "$ANWIND_CMD_FIFO" ]; then
        ( printf '%s\n' "$*" > "$ANWIND_CMD_FIFO" & ) 2>/dev/null
    else
        echo "anwind: 命令桥不可用（App 未运行或 FIFO 缺失）" >&2
        return 1
    fi
}

theme() {
    if [ $# -eq 0 ]; then
        echo "用法: theme win95|xp|win7|win10|win11"
        return 1
    fi
    _anwind_send "theme $*"
}

start() {
    if [ $# -eq 0 ]; then
        echo "用法: start <应用名>，运行 apps 查看列表"
        return 1
    fi
    _anwind_send "start $*"
}

apps() {
    _anwind_send "apps"
}

open() {
    if [ $# -eq 0 ]; then
        echo "用法: open <url>"
        return 1
    fi
    _anwind_send "open $*"
}

winver() {
    _anwind_send "winver"
    echo "AnWind ${ANWIND_VERSION:-2.22.1} (Termux ${TERMUX_VERSION:-0.118.0} 移植)"
}
