revision="1.1.6"
url="https://xorg.freedesktop.org/archive/individual/lib/libXdamage-${revision}.tar.xz"
urlType="tar"
arch="aarch64 x86_64"
buildSys="autotools"
license="MIT"
deps="libX11 libXfixes xorgproto"
